//go:build ignore

// types_generate.go is meant to run with go generate. It will use go/{importer,types} to track down all the RR struct
// types. Then for each type it will generate conversion tables for String() and banal methods (len, Header, copy) based
// on the struct tags. The generated source is written to ztypes.go, and is meant to be checked into git.

package main

import (
	"bytes"
	"fmt"
	"go/types"
	"log"
	"strings"
	"text/template"

	"github.com/miekg/dnsv2/internal/generate"
)

var hdr = `
// Code generated by "go run types_generate.go"; Edits will be lost.

package dns

import (
	"encoding/binary"
	"strconv"
)

`

var (
	typeToRR = template.Must(template.New("typeToRR").Parse(`
// TypeToRR is a mapping from Type to a function that returns the type.
var TypeToRR = map[Type]func() RR{
{{range .}}  Type{{.}}:  func() RR { return new({{.}}) },
{{end}}
}
`))

	// Interface implementation check for all RRs.
	iface = template.Must(template.New("iface").Parse(`
var (
{{range .}} _ RR = new({{.}})
{{end}}
)
`))

	// RRtype
	rrtype = template.Must(template.New("rrtype").Parse(`
// RRToType returns the type of the RR.
func RRToType(rr RR) Type {
	switch rr.(type) {
{{range .}} case *{{.}}:
	return Type{{.}}
{{end}} }
	return TypeNone
}
`))

	headerFunc = template.Must(template.New("headerFunc").Parse(`
{{range .}}  func (rr *{{.}}) Hdr() *Header { return &rr.Header }
{{end}}
`))

	// Type
	typeStr = template.Must(template.New("str").Funcs(generate.Funcs).Parse(`
// TypeToString maps Types to strings.
var TypeToString = map[Type]string{
{{range .}} Type{{.}}: "{{.|ToUpper}}",
{{end}}
}

// StringToType maps strings to Types.
var StringToType = reverseType(TypeToString)

// String returns the string representation for Type t, unknown Types return TYPE<num>.
func (t Type) String() string {
	if s, ok := TypeToString[t]; ok {
		return s
	}
	i := binary.BigEndian.Uint16(t[:])
	return "TYPE" + strconv.FormatUint(uint64(i), 10)
}
`))

	// Rcode
	rcodeStr = template.Must(template.New("rcodeStr").Funcs(generate.Funcs).Parse(`
// RcodeToString maps Rcodes to strings.
var RcodeToString = map[Rcode]string{
{{range .}} Rcode{{.}}: "{{.|ToUpper}}",
{{end}}
}

// StringToRcode maps strings to Rcodes.
var StringToRcode = reverseRcode(RcodeToString)

// String returns the string representation for Rcode r, unknown Rcodes return RCODE<num>.
func (r Rcode) String() string {
	if s, ok := RcodeToString[r]; ok {
		return s
	}
	return "RCODE" + strconv.FormatUint(uint64(r), 10)
}
`))

	// Opcode
	opcodeStr = template.Must(template.New("opcodeStr").Funcs(generate.Funcs).Parse(`
// OpcodeToString maps Opcodes to strings.
var OpcodeToString = map[Opcode]string{
{{range .}} Opcode{{.}}: "{{.|ToUpper}}",
{{end}}
}

// StringToOpcode maps strings to Opcodes.
var StringToOpcode = reverseOpcode(OpcodeToString)

// String returns the string representation for Opcode o, unknown opcodes return OPCODE<num>.
func (o Opcode) String() string {
	if s, ok := OpcodeToString[o]; ok {
		return s
	}
	return "OPCODE" + strconv.FormatUint(uint64(o), 10)
}
`))
	// Flag String()
	flagStr = template.Must(template.New("flagStr").Funcs(generate.Funcs).Parse(`
func (f Flag) String() string {
	switch f {
{{range .}}  case {{.}}:
	return "{{. | ToLower}}"
{{end}} }
	return ""
}
`))
	// Class
	classStr = template.Must(template.New("classStr").Funcs(generate.Funcs).Parse(`
// ClassToString maps Classes to strings.
var ClassToString = map[Class]string{
{{range .}} {{.}}: "{{.|ToUpper}}",
{{end}}
}

// StringToClass maps strings to Classes.
var StringToClass = reverseClass(ClassToString)

// String returns the string representation for Class c, unknown opcodes return CLASS<num>.
func (c Class) String() string {
	if s, ok := ClassToString[c]; ok {
		return s
	}
	i := binary.BigEndian.Uint16(c[:])
	return "CLASS" + strconv.FormatUint(uint64(i), 10)
}
`))
)

func main() {
	pkg, err := generate.Load()
	if err != nil {
		log.Fatal(err)
	}
	typex := generate.Types(pkg, "Type")

	b := &bytes.Buffer{}
	b.WriteString(hdr)

	if err := typeToRR.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "typeToRR", err)
	}
	if err := iface.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "iface", err)
	}
	if err := headerFunc.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "headerFunc", err)
	}
	if err := rrtype.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "rrtype", err)
	}
	if err := typeStr.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "typeStr", err)
	}

	Len(b, pkg)
	Data(b, pkg)

	rcodex := generate.Types(pkg, "Rcode")
	if err := rcodeStr.Execute(b, rcodex); err != nil {
		log.Fatal("failed to generate %s: %s", "rcodeStr", err)
	}

	opcodex := generate.Types(pkg, "Opcode")
	if err := opcodeStr.Execute(b, opcodex); err != nil {
		log.Fatal("failed to generate %s: %s", "opcodeStr", err)
	}

	// doeesnt'find the correct types, Need Flag _TYPES_
	flagx := generate.TypesOf(pkg, "Flag")
	if err := flagStr.Execute(b, flagx); err != nil {
		log.Fatal("failed to generate %s: %s", "flagStr", err)
	}

	classx := generate.TypesOf(pkg, "Class")
	if err := classStr.Execute(b, classx); err != nil {
		log.Fatal("failed to generate %s: %s", "classStr", err)
	}

	if err := generate.SaveSource(b.Bytes(), "ztypes.go"); err != nil {
		log.Printf("%s\n", b)
		log.Fatal("failed to save source: %s", err)
	}
}

// Generate the Len() methods. We return the number of fields for each resource record, except when the struct tag
// `dns:"len"` is seen, then we take the 'len()' of the field.
func Len(b *bytes.Buffer, pkg *types.Package) {
	typex := generate.Types(pkg, "Type")
	scope := pkg.Scope()

	for _, name := range typex {
		o := scope.Lookup(name)
		rr := generate.RR(o.Type(), scope)
		if rr == nil {
			continue
		}

		fmt.Fprintf(b, "func (rr *%s) Len() int {\n", name)

		l := 0
		dyn := []string{}
		for i := 1; i < rr.NumFields(); i++ {
			switch {
			case strings.Contains(rr.Tag(i), "len"):
				dyn = append(dyn, fmt.Sprintf("len(rr.%s)", rr.Field(i).Name()))
			default:
				l++
			}
		}
		if len(dyn) > 0 {
			fmt.Fprintf(b, "return %d + %s\n}\n", l, strings.Join(dyn, "+"))
			continue
		}
		fmt.Fprintf(b, "return %d\n}\n", l)
	}
}

// Generate the Data methods where the rdata 'i' is returned as a byte slice.
func Data(b *bytes.Buffer, pkg *types.Package) {
	typex := generate.Types(pkg, "Type")
	scope := pkg.Scope()

Types:
	for _, name := range typex {
		o := scope.Lookup(name)
		rr := generate.RR(o.Type(), scope)
		if rr == nil {
			continue
		}

		// check if this type doesn't need a Data() method to be generated.
		for i := 1; i < rr.NumFields(); i++ {
			if strings.Contains(rr.Tag(i), "-data") {
				continue Types
			}
		}

		fmt.Fprintf(b, "func (rr *%s) Data(i int) []byte {\nswitch i {\n", name)

		for i := 1; i < rr.NumFields(); i++ {

			fmt.Fprintf(b, "case %d:\n", i-1)

			switch rr.Field(i).Type().(type) {
			case *types.Slice:
				fmt.Fprintf(b, "return rr.%s\n", rr.Field(i).Name())
			case *types.Array:
				fmt.Fprintf(b, "return rr.%s[:]\n", rr.Field(i).Name())
			default:
				// check name before panicking
				switch rr.Field(i).Type().String() {
				case generate.Import + ".Name":
					fmt.Fprintf(b, "return rr.%s\n", rr.Field(i).Name())
				default:
					panic("types_generate: unhandled type: " + rr.Field(i).Type().String())
				}
			}
		}
		fmt.Fprintf(b, "}\nreturn nil\n}\n")
	}
}
