//go:build ignore

// rr_generate generates zrr.go which houses all the methods that implement the RR interface.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"html/template"
	"log"
	"os"

	"github.com/miekg/dns/internal/generate"
)

var hdr = `
// Code generated by "go run rr_generate.go"; DO NOT EDIT.

package dns

`

var TypeToRR = template.Must(template.New("TypeToRR").Parse(`
// TypeToRR is a map of constructors for each RR type.
var TypeToRR = map[uint16]func() RR{
{{range .}}{{if ne . "RFC3597"}}  Type{{.}}:  func() RR { return new({{.}}) },
{{end}}{{end}}                    }

`))

var RRToType = template.Must(template.New("RRToType").Parse(`
// RRToType is the reverse of TypeToRR, implemented as a function.
func RRToType(rr RR) uint16 {
    switch rr.(type) {
{{range .}}{{if ne . "RFC3597"}}  case *{{.}}:
	return Type{{.}}
{{end}}{{end}} }
	// if here, we don't have the RR in our lef
    return TypeNone
}

`))

var headerFunc = template.Must(template.New("headerFunc").Parse(`
{{range .}}  func (rr *{{.}}) Header() *Header { return &rr.Hdr }
{{end}}

`))

const out = "_zrr.go" // does not work for checking the struct tags yet. TMP TODO

var flagDebug = flag.Bool("debug", false, "Emit the non-formatted code to standard output and do not write it to a file.")

func main() {
	flag.Parse()
	types, err := generate.ExportedTypes("types.go")
	if err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}

	source := &bytes.Buffer{}
	source.WriteString(hdr)
	if err := headerFunc.Execute(source, types); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	if err := TypeToRR.Execute(source, types); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	if err := RRToType.Execute(source, types); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}

	if *flagDebug {
		fmt.Print(source.String())
		return
	}

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		source.WriteTo(os.Stderr)
		log.Fatalf("Failed to generate %s: %v", out, err)
	}

	if err := os.WriteFile(out, formatted, 0640); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
}
