//go:build ignore

// rr_generate generates zrr.go which houses all the methods that implement the RR interface.

package main

import (
	"bytes"
	"flag"
	"html/template"
	"log"
	"strings"

	"github.com/miekg/dnsv2/internal/generate"
)

var hdr = `
// Code generated by "go run rr_generate.go"; DO NOT EDIT.

package dns

`

var TypeToRR = template.Must(template.New("TypeToRR").Parse(`
// TypeToRR is a map of constructors for each RR type.
var TypeToRR = map[uint16]func() RR{
{{range .}}{{if ne . "RFC3597"}}  Type{{.}}:  func() RR { return new({{.}}) },
{{end}}{{end}}                    }

`))

var RRToType = template.Must(template.New("RRToType").Parse(`
// RRToType is the reverse of TypeToRR, implemented as a function.
func RRToType(rr RR) uint16 {
    switch rr.(type) {
{{range .}}{{if ne . "RFC3597"}}  case *{{.}}:
	return Type{{.}}
{{end}}{{end}} }
	// if here, we don't have the RR in our pkg, check if it does Typer.
	if x, ok := rr.(Typer); ok {
		return x.Type()
	}
    return TypeNone
}

`))

var TypeToString = template.Must(template.New("typeToString").Parse(`
// TypeToString is a map of strings for each RR type.
var TypeToString = map[uint16]string{
{{range .}}{{if ne . "NSAPPTR"}}  Type{{.}}: "{{.}}",
{{end}}{{end}}                    TypeNSAPPTR:    "NSAP-PTR",
}

`))

var headerFunc = template.Must(template.New("headerFunc").Parse(`
{{range .}}  func (rr *{{.}}) Header() *Header { return &rr.Hdr }
{{end}}

`))

var funcMap = template.FuncMap{
	"join": strings.Join,
}

var fieldFunc = template.Must(template.New("fieldFunc").Funcs(funcMap).Parse(`
{{range $t, $fs := .}}  func (rr *{{$t}}) Data() []Field { return []Field{ {{join $fs ","}} }}
{{end}}

`))

const out = "zrr.go"

func main() {
	flag.Parse()
	types, err := generate.Types("types.go")
	if err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}

	source := &bytes.Buffer{}
	source.WriteString(hdr)
	if err := headerFunc.Execute(source, types); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	if err := TypeToRR.Execute(source, types); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	if err := RRToType.Execute(source, types); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	if err := TypeToString.Execute(source, types); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}

	fields, err := generate.Fields("types.go")
	if err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	if err := fieldFunc.Execute(source, fields); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}

	generate.Write(source, out)
}
