//+build ignore

// types_generate.go is meant to run with go generate. It will use go/{importer,types} to track down all the RR struct
// types. Then for each type it will generate conversion tables (typeToRR and TypeToString) and banal methods (len,
// Header, copy) based on the struct tags. The generated source is written to ztypes.go, and is meant to be checked into
// git.

package main

import (
	"bytes"
	"fmt"
	"go/types"
	"log"
	"strings"
	"text/template"

	"github.com/miekg/dnsv2/internal/generate"
)

var hdr = `
// Code generated by "go run types_generate.go"; Edits will be lost.

package dns

`

var (
	// typeToRR map.
	typeToRR = template.Must(template.New("typeToRR").Parse(`
var typeToRR = map[Type]func() RR{
{{range .}}  Type{{.}}:  func() RR { return new({{.}}) },
{{end}}
}

`))

	// TypeToString map.
	typeToString = template.Must(template.New("typeToString").Parse(`
// TypeToString is a map of strings for each RR type.
var TypeToString = map[Type]string{
{{range .}}  Type{{.}}: "{{.}}",
{{end}}
}

`))

	// Interface implementation check for all RRs.
	iface = template.Must(template.New("iface").Parse(`
var (
{{range .}} _ RR = new({{.}})
{{end}}
)
`))

	// RRtype
	rrtype = template.Must(template.New("rrtype").Parse(`
// RRType returns the type of the RR.
func RRType(rr RR) Type {
	switch rr.(type) {
{{range .}} case *{{.}}:
	return Type{{.}}
{{end}} }
	return TypeNone
}
`))

	headerFunc = template.Must(template.New("headerFunc").Parse(`
{{range .}}  func (rr *{{.}}) Hdr() *Header { return &rr.Header }
{{end}}
`))

	str = template.Must(template.New("str").Parse(`
func (t Type) String() string {
	switch t {
{{range .}}  case Type{{.}}:
	return "{{.}}"
{{end}} }
	return "NONE"
}
`))
)

func main() {
	pkg, err := generate.Load()
	if err != nil {
		log.Fatal(err)
	}
	typex := generate.Types(pkg, "Type")

	b := &bytes.Buffer{}
	b.WriteString(hdr)

	if err := typeToRR.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "typeToRR", err)
	}
	if err := typeToString.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "TypeToString", err)
	}
	if err := iface.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "iface", err)
	}
	if err := headerFunc.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "headerFunc", err)
	}
	if err := rrtype.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "rrtype", err)
	}
	if err := str.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "str", err)
	}

	Len(b, pkg)

	if err := generate.SaveSource(b.Bytes(), "ztypes.go"); err != nil {
		log.Fatal("failed go save source: %s", err)
	}
}

// Generate the Len() methods. We returns the number of fields for each resource record, except when the struct tag
// `dns:"len"` is seen, then we take the 'len()' of the field.
func Len(b *bytes.Buffer, pkg *types.Package) {
	typex := generate.Types(pkg, "Type")
	scope := pkg.Scope()

	for _, name := range typex {
		o := scope.Lookup(name)
		rr := generate.RR(o.Type(), scope)
		if rr == nil {
			continue
		}

		fmt.Fprintf(b, "func (rr *%s) Len() int {\n", name)

		l := 0
		dyn := []string{}
		for i := 1; i < rr.NumFields(); i++ {
			switch rr.Tag(i) {
			case `dns:"len"`:
				dyn = append(dyn, fmt.Sprintf("len(rr.%s)", rr.Field(i).Name()))
			default:
				l++
			}
		}
		if len(dyn) > 0 {
			fmt.Fprintf(b, "return %d + %s\n}", l, strings.Join(dyn, "+"))
			continue
		}
		fmt.Fprintf(b, "return %d\n}\n", l)
	}
}
