//+build ignore

// types_generate.go is meant to run with go generate. It will use go/{importer,types} to track down all the RR struct
// types. Then for each type it will generate conversion tables (typeToRR and TypeToString) and banal methods (len,
// Header, copy) based on the struct tags. The generated source is written to ztypes.go, and is meant to be checked into
// git.

package main

import (
	"bytes"
	"go/types"
	"log"
	"strings"
	"text/template"

	"github.com/miekg/dnsv2/internal/generate"
)

var hdr = `
// Code generated by "go run types_generate.go"; Edits will be lost.

package dns

`

var (
	// typeToRR map.
	typeToRR = template.Must(template.New("typeToRR").Parse(`
var typeToRR = map[Type]func() RR{
{{range .}}  Type{{.}}:  func() RR { return new({{.}}) },
{{end}}
}

`))

	// TypeToString map.
	typeToString = template.Must(template.New("typeToString").Parse(`
// TypeToString is a map of strings for each RR type.
var TypeToString = map[Type]string{
{{range .}}  Type{{.}}: "{{.}}",
{{end}}
}

`))

	// Interface implementation check for all RRs.
	iface = template.Must(template.New("iface").Parse(`
var (
{{range .}} _ RR = new({{.}})
{{end}}
)
`))

	// RRtype
	rrtype = template.Must(template.New("rrtype").Parse(`
// RRType returns the type of the RR.
func RRType(rr RR) Type {
	switch rr.(type) {
{{range .}} case *{{.}}:
	return Type{{.}}
{{end}} }
	return TypeNone
}
`))
)

func main() {
	pkg, err := generate.Load()
	if err != nil {
		log.Fatal(err)
	}
	typex := Types(pkg)

	b := &bytes.Buffer{}
	b.WriteString(hdr)

	if err := typeToRR.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "typeToRR", err)
	}
	if err := typeToString.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "TypeToString", err)
	}
	if err := iface.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "iface", err)
	}
	if err := rrtype.Execute(b, typex); err != nil {
		log.Fatal("failed to generate %s: %s", "rrtype", err)
	}
	generate.SaveSource(b.Bytes(), "ztypes.go")
}

func Types(pkg *types.Package) []string {
	scope := pkg.Scope()
	// Collect constants like TypeX
	var typex []string
	for _, name := range scope.Names() {
		o := scope.Lookup(name)
		if o == nil || !o.Exported() {
			continue
		}
		if !strings.HasPrefix(o.Name(), "Type") {
			continue
		}
		name := strings.TrimPrefix(o.Name(), "Type")
		if name == "" || name == "None" {
			continue
		}
		if o.Type().String() != generate.Import+".Type" {
			continue
		}
		typex = append(typex, name)
	}
	return typex
}
