// Code generated by "go run ednsrr_generate.go"; DO NOT EDIT.

package dns

func (rr *NSID) Header() *Header    { return &rr.Hdr }
func (rr *NSID) Pseudo() bool       { return true }
func (rr *PADDING) Header() *Header { return &rr.Hdr }
func (rr *PADDING) Pseudo() bool    { return true }

// CodeToRR is a map of constructors for each EDNS0 RR type.
var CodeToRR = map[uint16]func() EDNS0{
	CodeNSID:    func() EDNS0 { return new(NSID) },
	CodePADDING: func() EDNS0 { return new(PADDING) },
}

// RRToCode is the reverse of CodeToRR, implemented as a function.
func RRToCode(rr EDNS0) uint16 {
	switch rr.(type) {
	case *NSID:
		return CodeNSID
	case *PADDING:
		return CodePADDING
	}
	return CodeNone
}

// CodeToString is a map of strings for each EDNS0 RR type.
var CodeToString = map[uint16]string{
	CodeNSID:    "NSID",
	CodePADDING: "PADDING",
}

func (rr *NSID) Data() []Field    { return []Field{rr.Nsid} }
func (rr *PADDING) Data() []Field { return []Field{rr.Padding} }
