// Code generated by "go run rr_generate.go"; DO NOT EDIT.

package dns

import (
	"github.com/miekg/dnsv2/dnswire"
)

func (rr *RFC3597) Name(x ...dnswire.Name) (dnswire.Name, error)    { return _Name(rr, x...) }
func (rr *RFC3597) Type(x ...dnswire.Type) (dnswire.Type, error)    { return _Type(rr, x...) }
func (rr *RFC3597) DataLen(x ...uint16) (uint16, error)             { return _DataLen(rr, x...) }
func (rr *RFC3597) Class(x ...dnswire.Class) (dnswire.Class, error) { return _Class(rr, x...) }
func (rr *RFC3597) TTL(x ...dnswire.TTL) (dnswire.TTL, error)       { return _TTL(rr, x...) }
func (rr *RFC3597) String() string                                  { return _String(rr) }
func (rr *RFC3597) Len() int                                        { return _Len(rr) }
func (rr *RFC3597) Octets(x ...[]byte) []byte {
	if len(x) == 0 {
		return rr.octets
	}
	rr.octets = x[0]
	return nil
}

func (rr *A) Name(x ...dnswire.Name) (dnswire.Name, error)    { return _Name(rr, x...) }
func (rr *A) Type(x ...dnswire.Type) (dnswire.Type, error)    { return _Type(rr, x...) }
func (rr *A) DataLen(x ...uint16) (uint16, error)             { return _DataLen(rr, x...) }
func (rr *A) Class(x ...dnswire.Class) (dnswire.Class, error) { return _Class(rr, x...) }
func (rr *A) TTL(x ...dnswire.TTL) (dnswire.TTL, error)       { return _TTL(rr, x...) }
func (rr *A) String() string                                  { return _String(rr) }
func (rr *A) Len() int                                        { return _Len(rr) }
func (rr *A) Octets(x ...[]byte) []byte {
	if len(x) == 0 {
		return rr.octets
	}
	rr.octets = x[0]
	return nil
}

func (rr *PTR) Name(x ...dnswire.Name) (dnswire.Name, error)    { return _Name(rr, x...) }
func (rr *PTR) Type(x ...dnswire.Type) (dnswire.Type, error)    { return _Type(rr, x...) }
func (rr *PTR) DataLen(x ...uint16) (uint16, error)             { return _DataLen(rr, x...) }
func (rr *PTR) Class(x ...dnswire.Class) (dnswire.Class, error) { return _Class(rr, x...) }
func (rr *PTR) TTL(x ...dnswire.TTL) (dnswire.TTL, error)       { return _TTL(rr, x...) }
func (rr *PTR) String() string                                  { return _String(rr) }
func (rr *PTR) Len() int                                        { return _Len(rr) }
func (rr *PTR) Octets(x ...[]byte) []byte {
	if len(x) == 0 {
		return rr.octets
	}
	rr.octets = x[0]
	return nil
}

func (rr *AAAA) Name(x ...dnswire.Name) (dnswire.Name, error)    { return _Name(rr, x...) }
func (rr *AAAA) Type(x ...dnswire.Type) (dnswire.Type, error)    { return _Type(rr, x...) }
func (rr *AAAA) DataLen(x ...uint16) (uint16, error)             { return _DataLen(rr, x...) }
func (rr *AAAA) Class(x ...dnswire.Class) (dnswire.Class, error) { return _Class(rr, x...) }
func (rr *AAAA) TTL(x ...dnswire.TTL) (dnswire.TTL, error)       { return _TTL(rr, x...) }
func (rr *AAAA) String() string                                  { return _String(rr) }
func (rr *AAAA) Len() int                                        { return _Len(rr) }
func (rr *AAAA) Octets(x ...[]byte) []byte {
	if len(x) == 0 {
		return rr.octets
	}
	rr.octets = x[0]
	return nil
}

func (rr *MX) Name(x ...dnswire.Name) (dnswire.Name, error)    { return _Name(rr, x...) }
func (rr *MX) Type(x ...dnswire.Type) (dnswire.Type, error)    { return _Type(rr, x...) }
func (rr *MX) DataLen(x ...uint16) (uint16, error)             { return _DataLen(rr, x...) }
func (rr *MX) Class(x ...dnswire.Class) (dnswire.Class, error) { return _Class(rr, x...) }
func (rr *MX) TTL(x ...dnswire.TTL) (dnswire.TTL, error)       { return _TTL(rr, x...) }
func (rr *MX) Len() int                                        { return _Len(rr) }
func (rr *MX) Octets(x ...[]byte) []byte {
	if len(x) == 0 {
		return rr.octets
	}
	rr.octets = x[0]
	return nil
}

func (rr *NS) Name(x ...dnswire.Name) (dnswire.Name, error)    { return _Name(rr, x...) }
func (rr *NS) Type(x ...dnswire.Type) (dnswire.Type, error)    { return _Type(rr, x...) }
func (rr *NS) DataLen(x ...uint16) (uint16, error)             { return _DataLen(rr, x...) }
func (rr *NS) Class(x ...dnswire.Class) (dnswire.Class, error) { return _Class(rr, x...) }
func (rr *NS) TTL(x ...dnswire.TTL) (dnswire.TTL, error)       { return _TTL(rr, x...) }
func (rr *NS) String() string                                  { return _String(rr) }
func (rr *NS) Len() int                                        { return _Len(rr) }
func (rr *NS) Octets(x ...[]byte) []byte {
	if len(x) == 0 {
		return rr.octets
	}
	rr.octets = x[0]
	return nil
}

func (rr *SOA) Name(x ...dnswire.Name) (dnswire.Name, error)    { return _Name(rr, x...) }
func (rr *SOA) Type(x ...dnswire.Type) (dnswire.Type, error)    { return _Type(rr, x...) }
func (rr *SOA) DataLen(x ...uint16) (uint16, error)             { return _DataLen(rr, x...) }
func (rr *SOA) Class(x ...dnswire.Class) (dnswire.Class, error) { return _Class(rr, x...) }
func (rr *SOA) TTL(x ...dnswire.TTL) (dnswire.TTL, error)       { return _TTL(rr, x...) }
func (rr *SOA) String() string                                  { return _String(rr) }
func (rr *SOA) Len() int                                        { return _Len(rr) }
func (rr *SOA) Octets(x ...[]byte) []byte {
	if len(x) == 0 {
		return rr.octets
	}
	rr.octets = x[0]
	return nil
}

func (rr *OPT) Name(x ...dnswire.Name) (dnswire.Name, error)    { return _Name(rr, x...) }
func (rr *OPT) Type(x ...dnswire.Type) (dnswire.Type, error)    { return _Type(rr, x...) }
func (rr *OPT) DataLen(x ...uint16) (uint16, error)             { return _DataLen(rr, x...) }
func (rr *OPT) Class(x ...dnswire.Class) (dnswire.Class, error) { return _Class(rr, x...) }
func (rr *OPT) TTL(x ...dnswire.TTL) (dnswire.TTL, error)       { return _TTL(rr, x...) }
func (rr *OPT) String() string                                  { return _String(rr) }
func (rr *OPT) Len() int                                        { return _Len(rr) }
func (rr *OPT) Octets(x ...[]byte) []byte {
	if len(x) == 0 {
		return rr.octets
	}
	rr.octets = x[0]
	return nil
}
