// Code generated by "go run strings_generate.go"; Edits will be lost.

package dns

import (
	"encoding/binary"
	"strconv"
)

func (rr *CNAME) String() string {
	return TypeCNAME.String() + "\t" + rr.Target.String()
}
func (rr *MX) String() string {
	xxx := binary.BigEndian.Uint16(rr.Preference[:])
	return TypeMX.String() + "\t" + strconv.FormatUint(uint64(xxx), 10) + " " + rr.Exchange.String()
}
func (rr *NS) String() string {
	return TypeNS.String() + "\t" + rr.Target.String()
}
func (rr *PTR) String() string {
	return TypePTR.String() + "\t" + rr.Target.String()
}
