// Code generated by "go run types_generate.go"; Edits will be lost.

package dns

var typeToRR = map[Type]func() RR{
	TypeA:     func() RR { return new(A) },
	TypeCNAME: func() RR { return new(CNAME) },
	TypeMX:    func() RR { return new(MX) },
	TypeOPT:   func() RR { return new(OPT) },
}

// TypeToString is a map of strings for each RR type.
var TypeToString = map[Type]string{
	TypeA:     "A",
	TypeCNAME: "CNAME",
	TypeMX:    "MX",
	TypeOPT:   "OPT",
}

var (
	_ RR = new(A)
	_ RR = new(CNAME)
	_ RR = new(MX)
	_ RR = new(OPT)
)

func (rr *A) Hdr() *Header     { return &rr.Header }
func (rr *CNAME) Hdr() *Header { return &rr.Header }
func (rr *MX) Hdr() *Header    { return &rr.Header }
func (rr *OPT) Hdr() *Header   { return &rr.Header }

// RRType returns the type of the RR.
func RRType(rr RR) Type {
	switch rr.(type) {
	case *A:
		return TypeA
	case *CNAME:
		return TypeCNAME
	case *MX:
		return TypeMX
	case *OPT:
		return TypeOPT
	}
	return TypeNone
}

func (t Type) String() string {
	switch t {
	case TypeA:
		return "A"
	case TypeCNAME:
		return "CNAME"
	case TypeMX:
		return "MX"
	case TypeOPT:
		return "OPT"
	}
	return "NONE"
}
func (rr *A) Len() int {
	return 1
}
func (rr *CNAME) Len() int {
	return 1
}
func (rr *MX) Len() int {
	return 2
}
func (rr *OPT) Len() int {
	return 0 + len(rr.Options)
}
func (rr *A) Data(i int) []byte {
	switch i {
	case 0:
		return rr.A[:]
	}
	return nil
}
func (rr *CNAME) Data(i int) []byte {
	switch i {
	case 0:
		return rr.Target
	}
	return nil
}
func (rr *MX) Data(i int) []byte {
	switch i {
	case 0:
		return rr.Preference[:]
	case 1:
		return rr.Mx
	}
	return nil
}
