// Code generated by "go run types_generate.go"; Edits will be lost.

package dns

import (
	"encoding/binary"
	"strconv"
)

// TypeToRR is a mapping from Type to a function that returns the type.
var TypeToRR = map[Type]func() RR{
	TypeA:     func() RR { return new(A) },
	TypeCNAME: func() RR { return new(CNAME) },
	TypeMX:    func() RR { return new(MX) },
	TypeNS:    func() RR { return new(NS) },
	TypeOPT:   func() RR { return new(OPT) },
	TypePTR:   func() RR { return new(PTR) },
	TypeSOA:   func() RR { return new(SOA) },
}

var (
	_ RR = new(A)
	_ RR = new(CNAME)
	_ RR = new(MX)
	_ RR = new(NS)
	_ RR = new(OPT)
	_ RR = new(PTR)
	_ RR = new(SOA)
)

func (rr *A) Hdr() *Header     { return &rr.Header }
func (rr *CNAME) Hdr() *Header { return &rr.Header }
func (rr *MX) Hdr() *Header    { return &rr.Header }
func (rr *NS) Hdr() *Header    { return &rr.Header }
func (rr *OPT) Hdr() *Header   { return &rr.Header }
func (rr *PTR) Hdr() *Header   { return &rr.Header }
func (rr *SOA) Hdr() *Header   { return &rr.Header }

// RRToType returns the type of the RR.
func RRToType(rr RR) Type {
	switch rr.(type) {
	case *A:
		return TypeA
	case *CNAME:
		return TypeCNAME
	case *MX:
		return TypeMX
	case *NS:
		return TypeNS
	case *OPT:
		return TypeOPT
	case *PTR:
		return TypePTR
	case *SOA:
		return TypeSOA
	}
	return TypeNone
}

// TypeToString maps Types to strings.
var TypeToString = map[Type]string{
	TypeA:     "A",
	TypeCNAME: "CNAME",
	TypeMX:    "MX",
	TypeNS:    "NS",
	TypeOPT:   "OPT",
	TypePTR:   "PTR",
	TypeSOA:   "SOA",
}

// StringToType maps strings to Types.
var StringToType = reverseType(TypeToString)

// String returns the string representation for Type t, unknown Types return TYPE<num>.
func (t Type) String() string {
	if s, ok := TypeToString[t]; ok {
		return s
	}
	i := binary.BigEndian.Uint16(t[:])
	return "TYPE" + strconv.FormatUint(uint64(i), 10)
}
func (rr *A) Len() int {
	return 1
}
func (rr *CNAME) Len() int {
	return 1
}
func (rr *MX) Len() int {
	return 2
}
func (rr *NS) Len() int {
	return 1
}
func (rr *OPT) Len() int {
	return 0 + len(rr.Options)
}
func (rr *PTR) Len() int {
	return 1
}
func (rr *SOA) Len() int {
	return 7
}
func (rr *A) Data(i int) []byte {
	switch i {
	case 0:
		return rr.A[:]
	}
	return nil
}
func (rr *CNAME) Data(i int) []byte {
	switch i {
	case 0:
		return rr.Target
	}
	return nil
}
func (rr *MX) Data(i int) []byte {
	switch i {
	case 0:
		return rr.Preference[:]
	case 1:
		return rr.Exchange
	}
	return nil
}
func (rr *NS) Data(i int) []byte {
	switch i {
	case 0:
		return rr.Target
	}
	return nil
}
func (rr *PTR) Data(i int) []byte {
	switch i {
	case 0:
		return rr.Target
	}
	return nil
}
func (rr *SOA) Data(i int) []byte {
	switch i {
	case 0:
		return rr.Ns
	case 1:
		return rr.Mbox
	case 2:
		return rr.Serial[:]
	case 3:
		return rr.Refresh[:]
	case 4:
		return rr.Retry[:]
	case 5:
		return rr.Expire[:]
	case 6:
		return rr.MinTTL[:]
	}
	return nil
}

// RcodeToString maps Rcodes to strings.
var RcodeToString = map[Rcode]string{
	RcodeFormErr:  "FORMERR",
	RcodeNXDomain: "NXDOMAIN",
	RcodeNoError:  "NOERROR",
	RcodeNotImp:   "NOTIMP",
	RcodeRefused:  "REFUSED",
	RcodeServFail: "SERVFAIL",
}

// StringToRcode maps strings to Rcodes.
var StringToRcode = reverseRcode(RcodeToString)

// String returns the string representation for Rcode r, unknown Rcodes return RCODE<num>.
func (r Rcode) String() string {
	if s, ok := RcodeToString[r]; ok {
		return s
	}
	return "RCODE" + strconv.FormatUint(uint64(r), 10)
}

// OpcodeToString maps Opcodes to strings.
var OpcodeToString = map[Opcode]string{
	OpcodeIQuery: "IQUERY",
	OpcodeNotify: "NOTIFY",
	OpcodeQuery:  "QUERY",
	OpcodeStatus: "STATUS",
	OpcodeUpdate: "UPDATE",
}

// StringToOpcode maps strings to Opcodes.
var StringToOpcode = reverseOpcode(OpcodeToString)

// String returns the string representation for Opcode o, unknown opcodes return OPCODE<num>.
func (o Opcode) String() string {
	if s, ok := OpcodeToString[o]; ok {
		return s
	}
	return "OPCODE" + strconv.FormatUint(uint64(o), 10)
}

func (f Flag) String() string {
	switch f {
	case AA:
		return "aa"
	case AD:
		return "ad"
	case CD:
		return "cd"
	case QR:
		return "qr"
	case RA:
		return "ra"
	case RD:
		return "rd"
	case TC:
		return "tc"
	case Z:
		return "z"
	}
	return ""
}

// ClassToString maps Classes to strings.
var ClassToString = map[Class]string{
	ANY:  "ANY",
	IN:   "IN",
	NONE: "NONE",
}

// StringToClass maps strings to Classes.
var StringToClass = reverseClass(ClassToString)

// String returns the string representation for Class c, unknown opcodes return CLASS<num>.
func (c Class) String() string {
	if s, ok := ClassToString[c]; ok {
		return s
	}
	i := binary.BigEndian.Uint16(c[:])
	return "CLASS" + strconv.FormatUint(uint64(i), 10)
}
