// Code generated by "go run writes_generate.go"; Edits will be lost.

package dns

import (
	"fmt"
)

func (rr *A) Write(msg []byte, offset, n int) (err error) {
	if offset+n >= len(msg) {
		return &WireError{fmt.Errorf("buffer size too small, need %d, got %d", offset+n, len(msg))}
	}
	rr.A[0] = msg[offset+0]
	rr.A[1] = msg[offset+1]
	rr.A[2] = msg[offset+2]
	rr.A[3] = msg[offset+3]
	return nil
}
func (rr *CNAME) Write(msg []byte, offset, n int) (err error) {
	rr.Target, offset, err = unpackName(msg, offset)
	if err != nil {
		return err
	}
	return nil
}
func (rr *MX) Write(msg []byte, offset, n int) (err error) {
	if offset+n >= len(msg) {
		return &WireError{fmt.Errorf("buffer size too small, need %d, got %d", offset+n, len(msg))}
	}
	rr.Preference[0] = msg[offset+0]
	rr.Preference[1] = msg[offset+1]
	offset += 2
	rr.Exchange, offset, err = unpackName(msg, offset)
	if err != nil {
		return err
	}
	return nil
}
func (rr *NS) Write(msg []byte, offset, n int) (err error) {
	rr.Target, offset, err = unpackName(msg, offset)
	if err != nil {
		return err
	}
	return nil
}
func (rr *PTR) Write(msg []byte, offset, n int) (err error) {
	rr.Target, offset, err = unpackName(msg, offset)
	if err != nil {
		return err
	}
	return nil
}
func (rr *SOA) Write(msg []byte, offset, n int) (err error) {
	rr.Ns, offset, err = unpackName(msg, offset)
	if err != nil {
		return err
	}
	offset++
	rr.Mbox, offset, err = unpackName(msg, offset)
	if err != nil {
		return err
	}
	offset++
	if offset+n >= len(msg) {
		return &WireError{fmt.Errorf("buffer size too small, need %d, got %d", offset+n, len(msg))}
	}
	rr.Serial[0] = msg[offset+0]
	rr.Serial[1] = msg[offset+1]
	rr.Serial[2] = msg[offset+2]
	rr.Serial[3] = msg[offset+3]
	offset += 4
	if offset+n >= len(msg) {
		return &WireError{fmt.Errorf("buffer size too small, need %d, got %d", offset+n, len(msg))}
	}
	rr.Refresh[0] = msg[offset+0]
	rr.Refresh[1] = msg[offset+1]
	rr.Refresh[2] = msg[offset+2]
	rr.Refresh[3] = msg[offset+3]
	offset += 4
	if offset+n >= len(msg) {
		return &WireError{fmt.Errorf("buffer size too small, need %d, got %d", offset+n, len(msg))}
	}
	rr.Retry[0] = msg[offset+0]
	rr.Retry[1] = msg[offset+1]
	rr.Retry[2] = msg[offset+2]
	rr.Retry[3] = msg[offset+3]
	offset += 4
	if offset+n >= len(msg) {
		return &WireError{fmt.Errorf("buffer size too small, need %d, got %d", offset+n, len(msg))}
	}
	rr.Expire[0] = msg[offset+0]
	rr.Expire[1] = msg[offset+1]
	rr.Expire[2] = msg[offset+2]
	rr.Expire[3] = msg[offset+3]
	offset += 4
	if offset+n >= len(msg) {
		return &WireError{fmt.Errorf("buffer size too small, need %d, got %d", offset+n, len(msg))}
	}
	rr.MinTTL[0] = msg[offset+0]
	rr.MinTTL[1] = msg[offset+1]
	rr.MinTTL[2] = msg[offset+2]
	rr.MinTTL[3] = msg[offset+3]
	return nil
}
